Django_MKarry/Django_MKarry/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from axf import urls as axf_url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(axf_url, namespace='axf')),
]

Django_MKarry/axf/urls.py
from django.conf.urls import url
from . import views
from Django_MKarry import settings
from django.views.static import serve

urlpatterns = [
    # 首页
    url(r'^main/$',views.main,name='main'),
    # 闪送超市
    url(r'^market/$',views.market,name='market'),
    # 我的
    url(r'^mine/$',views.mine,name='mine'),
    url(r'^register/$',views.register,name='register'),
    url(r'^checkuserid/$',views.checkuserid,name='checkuserid'),
    url(r'^login/$',views.login,name='login'),
    url(r'^checkuserlogin/$',views.checkuserlogin,name="checkuserlogin"),
    #退出登陆
    url(r'^quit/$',views.quit,name='quit'),
    # 图片上传的路径
    url(r'^static/(.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    #购物车
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^changecart/(\d+)/$',views.changecart)


]

Django_MKarry/axf/models.py
from django.db import models

# Create your models here.
class Wheel(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=10)

class Nav(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=10)

class mustbuy (models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=10)

class Shop(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    pd = models.CharField(max_length=100)


class FoodTypes(models.Model):
    typeid = models.CharField(max_length=10)
    typename = models.CharField(max_length=20)
    childtypenames = models.CharField(max_length=150)
    typesort = models.IntegerField()


class Goods(models.Model):
    # 商品id
    productid = models.CharField(max_length=10)
    productimg = models.CharField(max_length=150)
    productname = models.CharField(max_length=50)
    productlongname = models.CharField(max_length=100)
    isxf = models.NullBooleanField(default=False)
    pmdesc = models.CharField(max_length=10)
    specifics = models.CharField(max_length=20)
    price = models.CharField(max_length=10)
    marketprice = models.CharField(max_length=10)
    categoryid = models.CharField(max_length=10)
    childcid = models.CharField(max_length=10)
    childcidname = models.CharField(max_length=10)
    dealerid = models.CharField(max_length=10)
    # 库存
    storenums = models.IntegerField()
    # 销量
    productnum = models.IntegerField()

class MainShow(models.Model):
    trackid = models.CharField(max_length=10)
    name = models.CharField(max_length=20)
    img = models.CharField(max_length=100)
    categoryid = models.CharField(max_length=10)
    brandname = models.CharField(max_length=20)

    img1 = models.CharField(max_length=100)
    childcid1 = models.CharField(max_length=10)
    productid1 = models.CharField(max_length=10)
    longname1 = models.CharField(max_length=50)
    price1 = models.CharField(max_length=10)
    marketprice1 = models.CharField(max_length=10)

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=10)
    productid2 = models.CharField(max_length=10)
    longname2 = models.CharField(max_length=50)
    price2 = models.CharField(max_length=10)
    marketprice2 = models.CharField(max_length=10)

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=10)
    productid3 = models.CharField(max_length=10)
    longname3 = models.CharField(max_length=50)
    price3 = models.CharField(max_length=10)
    marketprice3 = models.CharField(max_length=10)

class User(models.Model):
    userAccount = models.CharField(max_length=20,unique=True)
    userPasswd = models.CharField(max_length=20)
    userName = models.CharField(max_length=20)
    userPhone = models.CharField(max_length=20)
    userAddress = models.CharField(max_length=100)
    userImg = models.CharField(max_length=150)
    userRank = models.IntegerField()

    # token 值验证，每次登陆都会更新
    userToken = models.CharField(max_length=50)
    @classmethod
    def createuser(cls,account,passwd,name,phone,address,img,rank,token):
        user = cls(userAccount=account,userPasswd=passwd,userName=name,userPhone=phone,userAddress=address,userImg=img,userRank=rank,userToken=token)
        return user


class Cart(models.Model):
    userid = models.CharField(max_length=10)
    productid = models.CharField(max_length=10)
    productnum = models.IntegerField()
    productprice = models.FloatField()
    productlongname = models.CharField(max_length=100)
    productimg = models.CharField(max_length=150)
    ischose = models.BooleanField()
    isdelete = models.BooleanField()

    @classmethod
    def createcart(cls,userid,productid,productnum,productprice,productlongname,productimg,ischose,isdelete,):
        cart = cls(userid=userid, productid=productid, productnum=productnum, productprice=productprice, productlongname=productlongname,
                   productimg=productimg, ischose=ischose, isdelete=isdelete)
        return cart

Django_MKarry/axf/views.py
from django.shortcuts import  render,redirect
import os
import time
import random
from django.contrib.auth import logout
from django.conf import settings
from .models import Wheel,Nav,mustbuy,Shop,FoodTypes,Goods,MainShow,User,Cart
import uuid
from django.http import JsonResponse
# 主页
def main(request):
    # 获取轮播数据
    loopList = Wheel.objects.all()
    # 导航数据
    navList = Nav.objects.all()
    # 每日必选
    buyList = mustbuy.objects.all()
    imgList = Shop.objects.all()
    quicksend = imgList[0]
    hotsell = imgList[1]
    newgoods = imgList[2]
    imgList1 = imgList[4:7]
    imgList2 = imgList[7:]

    # 商品列表
    mainList = MainShow.objects.all()

    context = {
        'loopWheelList': loopList,
        'navList': navList,
        'buyList': buyList,
        'quicksend':quicksend,
        'hotsell':hotsell,
        'newgoods':newgoods,
        'imgList1':imgList1,
        'imgList2':imgList2,
        'mainList':mainList,
    }
    return render(request,'axf/main.html',context)

# 闪送超市
def market(request):
    # pageid    cid    sortid   是从网页访问的url中获取的
    #左侧数据
    leftList = FoodTypes.objects.all()
    pageid = request.GET.get('id')
    cid = request.GET.get('cid')
    sortid = request.GET.get('sortid')
    print(pageid,cid,sortid)

    # goodsList = Goods.objects.all()
    if pageid != '104749':
        pageid = request.GET.get('id')
        print(pageid)

    #右侧数据
    if cid == '0':
        goodsList = Goods.objects.filter(categoryid=pageid)
    else:
        goodsList = Goods.objects.filter(categoryid=pageid, childcid=cid)

    # 排序goodsList  sortid:表示前台界面排序的几种方式：按价格、按销量、、
    if sortid == '0':
        goodsList = goodsList.order_by('productid')
    elif sortid == '1':
        goodsList = goodsList.order_by('productnum')
    elif sortid == '2':
        goodsList = goodsList.order_by('price').reverse()
    elif sortid == '3':
        goodsList = goodsList.order_by('price')

    # 子类名称
    fllist = []
    foodtype = FoodTypes.objects.get(typeid=pageid)
    allcname = foodtype.childtypenames
    # #全部分类:0#酸奶乳酸菌:103537#牛奶豆浆:103538#面包蛋糕:103540
    idnames = allcname.split("#")
    for str in idnames:
        arr = str.split(':')
        fllist.append({'code':arr[1],'title':arr[0]})
        cid = arr[1]
    # print(fllist,'-------------------')

    titleList = [{'title':'综合排序','index':'0'},{'title':'销量排序','index':'1'},
                 {'title':'价格最低','index':'2'},{'title':'价格最高','index':'3'}]

    return render(request,'axf/market.html',{'title':'闪送超市','leftList':leftList, 'goodsList':goodsList,
                                             'titleList':titleList,'id':pageid,'fllist':fllist,'cid':cid,'sortid':sortid})

# 购物车
def cart(request):
    token = request.session.get('token')
    # print("*******************************")
    # print("token:",token)
    if token == None:
        return render(request,'axf/login.html')
    user = User.objects.get(userToken=token)
    userid = user.userAccount
    cartlist = Cart.objects.filter(userid=userid)
    print("*******************************")
    print(cartlist)
    context = {
        'username':user.userName,
        'userphone':user.userPhone,
        'useraddress':user.userAddress,
        'cartlist':cartlist
    }

    return render(request,'axf/cart.html',context)

def changecart(request,flag):
    print(flag,"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    #判断是否登录
    token = request.session.get('token')
    # print("-----------------token:",token)
    # token==None   没有登录
    if token == None:
        return JsonResponse({'data':"0","status":'error'})

    #用户登录后
    # 通过token获取用户的信息userToken
    user = User.objects.get(userToken=token)
    #用户id
    userid = user.userAccount
    #商品id
    # 从前台ajax传来的参数中获取（ajax传参一般是post、get两种方式，此处是post传回的）
    productid = request.POST.get("productid")
    #善品信息
    product = Goods.objects.get(productid=productid)
    #从购物车里获取数据展示在界面上
    carts = Cart.objects.filter(userid=userid,productid=productid)
   #没有商品数据   就将获取的数据传入数据库
    if carts.count() == 0:
        onecart = Cart.createcart(userid,productid,1,product.price,product.productlongname,product.productimg,True,False)
        onecart.save()
        return JsonResponse({'data':onecart.productnum,"status":"success"})
    else:
        c = carts[0]
        if flag == '0':
            print('执行到此处2--------')
            #增加
            if product.storenums != 0:
                c.productnum = c.productnum + 1
                print(c.productnum)
                product.storenums -= 1
                newprice = float(product.price)*c.productnum
                newprice = "%.2f"%newprice
                c.save()
                product.save()

        elif flag == '1':
            #减少
            c.productnum = c.productnum - 1
            product.storenums += 1
            product.save()
            if c.productnum == 0:
                c.delete()
                return JsonResponse({"data":0,"status":"success"})
            else:
                newprice = float(product.price) * c.productnum
                newprice = "%.2f"%newprice
                c.save()
        elif flag == "2":
            c.ischose = not c.ischose
            c.save()
            if c.ischose:
                str = '√'
            else:
                str=''
            return JsonResponse({'data':str,'status':'success'})
        elif flag == "3":
            if c.ischose:
                str = "√"
            return JsonResponse({"data":0,"status":'success'})

        return JsonResponse({'data':c.productnum,'status':'success'})



# 我的
def mine(request):
    token = request.session.get('token')
    print(token, "--------------------------")
    if token == None:
        # username = request.session.get('userName','未登陆')
        # return render(request,'axf/mine.html',{"username":username})
        return redirect("/login/")

    un = User.objects.get(userToken=token)
    un = un.userName
    username = un
    # print(username,'~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    return render(request,'axf/mine.html',{"username":username})

# 注册界面
def register(request):
    if request.method == 'GET':
        return render(request,'axf/register.html')
    if request.method == 'POST':
        userAccount = request.POST.get('userAccount')
        userPass = request.POST.get('userPass')
        userPasswd = request.POST.get('userPasswd')
        userName = request.POST.get('userName')
        # print('#################userName:',userName)
        userPhone = request.POST.get('userPhone')
        userAdderss = request.POST.get('userAdderss')
        f = request.FILES.get('picture')
        # print('------------------f:',f)
        # http://img01.bqstatic.com/upload/goods/000/001/1538/0000011538_41480.jpg@200w_200h_90Q
        # fname = str(uuid.uuid4())+'.jpg'
        fname = str(userAccount)+'.jpg'
        dname = 'static\\media\\' + fname
        imgpath = os.path.join(settings.BASE_DIR,dname)

        print(imgpath)
        with open(imgpath,'wb') as img:
            # chunks:块   调用这个函数自动将img分成几块   循环遍历将图片写入到img路径中
            for data in f.chunks():
                img.write(data)
        print(img)
        # 密码、用户编号 不被每次访问时被中间截获 利用
        token = time.time() + random.randint(1,10000)
        token = '%f'%token

        user = User.createuser(userAccount,userPass,userName,userPhone,userAdderss,imgpath,0,token)
        user.save()
        # 保存一下昵称，token  为了用户下次登录时的验证
        request.session['userName'] = userName
        # print("-----------------------username:",userName)
        request.session['token'] = token

    return redirect('/login/')
    # return  render(request,'axf/login.html')


# 验证用户的id是否可用
def checkuserid(request):
    userid = request.POST.get('checkid')
    try:
        use = User.objects.get(userAccount=userid)
    except User.DoesNotExist as e:
         # 该用户是新人
        return JsonResponse({'data':0,'status':'success'})
    #该用户已存在
    return JsonResponse({'data':1,'status':'error'})
#退出登陆
def quit(request):
    logout(request)
    return redirect('/main/')
def login(request):
    return render(request,'axf/login.html',{"title":"登陆"})
def checkuserlogin(request):
    username = request.POST.get('ua',None)
    userpasswd = request.POST.get('up')

    try:
        user = User.objects.get(userAccount=username)
    except User.DoesNotExist as e:
        return JsonResponse({'data':0,"status":"error"})

    if userpasswd != user.userPasswd:
        return JsonResponse({"data":1,"status":"error"})

    request.session['username'] = user.userName
    request.session['token'] = user.userToken
    return JsonResponse({"data":0,"status":"success"})

Django_MKarry/templates/axf/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<link>
    <meta charset="UTF-8">
    <title>{{title}}</title>

    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">

    <link rel="stylesheet" type="text/css" href="{% static 'base/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/swiper.min.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/reset.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/base.css'%}" />

    <script type="text/javascript" charset="utf-8" src="{% static 'base/js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'base/js/swiper.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'base/js/base.js' %}"></script>

    {% block linkscript %}
    {% endblock linkscript %}

<body>
    <header></header>

    <div id="box">
        {% block base %}
        {% endblock base %}
    </div>

    <footer>
        <a class="main" href="/main/">
            <dl>
                <dt><span></span></dt>
                <dd>主页</dd>
            </dl>
        </a>
        <a class="market" href="{% url 'axf:market' %}?id=104749&cid=0&sortid=0">
            <dl>
                <dt><span></span></dt>
                <dd>闪送超市</dd>
            </dl>
        </a>
        <a class="cart" href="{% url 'axf:cart' %}">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a class="mine" href="/mine/">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
</body>
</html>

Django_MKarry/templates/axf/cart.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}

{% block linkscript %}

    <link rel="stylesheet" type="text/css" href="{% static 'cart/css/cart.css' %}" />
    <script type="text/javascript" src="{% static 'cart/js/cart.js' %}"></script>

{% endblock linkscript %}

{% block base %}
<div id="cart">
    <h3><b>购物车</b></h3>
    <section class="full">
        <section>
            <ul>
                <li>
                    <div class="clear">
                        <p class="infoJustify"><b>昵称</b></p><p>: <span>{{ username }}</span></p>
                    </div>
                </li>
                <li>
                    <div class="clear"><p class="infoJustify"> <b>电话</b></p><p>: <span>{{ userphone }}</span><a
                            href="#" class="change">修改</a></p>
                    </div>
                </li>
                <li>
                    <div class="clear">
                        <p class="infoJustify">收货地址 <b></b></p><p>: <span>{{ useraddress }}</span><a
                            href="" class="change">修改</a></p>
                    </div>
                </li>
            </ul>
        </section>
        <section class="bill">
            <p>闪送超市</p>
            <p>￥0起送,22:00前满￥30免运费</p>
            <a href="#">凑单专区</a>
        </section>
        <section class="delivery">
            <span>收获备注</span>
            <input type="text" placeholder="可输入100字以内特殊要求内容">
        </section>
        <menu>
            <ul>
                {% for item in cartlist %}
                    <li class="menuList">
                        <div class="confirm">
                            <span class="ischose" goodsid="{{ item.productid }}">
                                <span id="{{item.productid}}a">
                                {% ifequal True item.isChose %}
                                    √
                                {% endifequal %}
                                </span>
                            </span>
                        </div>
                            <a href="#">
                            <img src="{{item.productimg}}"/>
                            <p>{{item.productname}}</p>
                            <span class="{{productprice}}"></span>
                        </a>
                        <section>
                            <button class="subShopping"  ga="{{item.productid}}">-</button>
                            <span id="{{item.productid}}">{{item.productnum}}</span>
                            <button class="addShopping"  ga="{{item.productid}}">+</button>
                        </section>
                    </li>
                {% endfor %}
            <li class="payTheBill">
						<div class="confirm"><span><span>
                            {% if trueFlag %}
                                √
                            {% endif %}
                        </span></span></div>
						<p><span>全选</span><span>共计:</span><span>总价</span><span>{{ newprice }}</span></p>
						<a href="#" id="ok">选好了</a>
            </li>
            </ul>
        </menu>

    </section>

</div>
{% endblock base %}

Django_MKarry/templates/axf/login.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}

{% block linkscript %}

    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/login.css' %}"/>
    <script type="text/javascript" src="{% static 'mine/js/login.js' %}"></script>
{% endblock linkscript %}

{% block base %}

    <div id="login">
        <a href="{% url 'axf:mine' %}"><p>&lt;返回</p></a>
        <div id="box">
            <form action="" method="post" class="form-horizontal">

                <div class="input-group">
                    <span class="input-group-addon">账号</span>
                    <input type="text" id="ui" class="form-control" aria-describedby="basic-addon1" name="userAccount" >

                </div>
                <div class="input-group">
                <span class="input-group-addon">密码</span>
                <input id="pi" type="text" class="form-control" aria-describedby="basic-addon1" name="userPasswd">
            </div>
            <button type="button" id="loginBtn">登录</button>
        </form>
        <p id="errorp">账号密码错误</p>
    </div>
    </div>

            </form>
        </div>
    </div>


{% endblock base %}

Django_MKarry/templates/axf/main.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}


{% block linkscript %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}" />
    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/main.js' %}"></script>
{% endblock linkscript %}


{% block base %}
<div id="main">
    {# 轮播 #}
    <section class="swiper-container" id="topSwiper">
        <div class="swiper-wrapper">
            {% for x in loopWheelList %}
                <div class="swiper-slide">
                    <a><img src="{{x.img}}"></a>
                </div>
            {% endfor %}
        </div>
        <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-
bullets"></div>
    </section>


    <section class="topMenu">
        <nav>
            <ul>
                {% for n in navList %}
                    <li>
                        <a>
                            <img src="{{n.img}}" />
                            <span>{{n.name}}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </nav>
        <menu class="swiper-container swiperMenu" id="swiperMenu">
            <ul class="swiper-wrapper">
                {% for n in nav2List %}
                    <li class="swiper-slide">
                        <a><img src="{{n.img}}" /></a>
                    </li>
                {% endfor %}
            </ul>
        </menu>
    </section>


    <!--13691511443-->
    <section class="CVS">
        <h2>
            <img src="{{quicksend.img}}" alt="{{quicksend.name}}"/>
        </h2>
        <fieldset>
                <a href="#">
                    <img src="{{hotsell.img}}" alt="{{hotsell.name}}"/>
                </a>
                <a href="#">
                    <img src="{{newgoods.img}}" alt="{{newgoods.name}}"/>
                </a>
        </fieldset>
        <ul>
            {% for x in imgList1 %}
                <li>
                    <a href="#">
                        <img src="{{x.img}}" />
                        <span>{{x.name}}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
        <ol>
            {% for x in imgList2 %}
                <li><a href="#"><img src="{{x.img}}" alt="{{x.name}}"/></a></li>
            {% endfor %}
        </ol>
    </section>

    <section class="mainInfo">
        {% for item in mainList %}
            <section>
                <h3>
                    {{item.name}}
                    <a href="#"> 更多> </a>
                    <span></span>
                </h3>
                <div>
                    <a href="#"><img src="{{item.img}}" alt="item.name"/></a>
                </div>
                <ul>
                    <li>
                        <a href="#">
                            <img src="{{item.img1}}"/>
                            <span class="description">{{item.longname1}}</span>
                            <span>¥{{item.price1}}</span>
                            <s>¥{{item.marketprice1}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{item.img2}}"/>
                            <span class="description">{{item.longname2}}</span>
                            <span>¥{{item.price2}}</span>
                            <s>¥{{item.marketprice2}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                    <li>
                        <a href="#">
                            <img src="{{item.img3}}"/>
                            <span class="description">{{item.longname3}}</span>
                            <span>¥{{item.price3}}</span>
                            <s>¥{{item.marketprice3}}</s>
                        </a>
                        <button><span>&#43;</span></button>
                    </li>
                </ul>
            </section>
        {% endfor %}
    </section>

</div>
{% endblock base %}

Django_MKarry/templates/axf/mine.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}

{% block linkscript %}
    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/mine.css' %}"/>
    <script type="text/javascript" charset="utf-8" src="{% static 'mine/js/mine.js' %}"></script>
{% endblock linkscript %}

{% block base %}
    <div id="mine">
    <section class="fixed">
        <span class="glyphicon glyphicon-user"></span>
        <p><a href="#">{{ username }}</a></p>
        <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
        <a href="{% url 'axf:register' %}" id="regis">注册</a>
        <p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
    </section>
    <section class="mine">
        <p>
            <span>我的订单</span><a>查看订单&gt;</a>
        </p>
        <nav id="nav">
            <ul>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-usd"></span></dt>
                            <dd>代付款</dd>
                        </dl>
                    </a>
                </li>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-envelope"></span></dt>
                            <dd>待收货</dd>
                        </dl>
                    </a>
                </li>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                            <dd>待评价</dd>
                        </dl>
                    </a>
                </li>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </a>
                </li>
            </ul>
        </nav>
        <menu>
            <ul>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                            <dd>积分商城</dd>
                        </dl>
                    </a>
                </li>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                            <dd>优惠劵</dd>
                        </dl>
                    </a>
                </li>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-import"></span></dt>
                            <dd>收货地址</dd>
                        </dl>
                    </a>
                </li>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                            <dd>客服/反馈</dd>
                        </dl>
                    </a>
                </li>
                <li>
                    <a>
                        <dl>
                            <dt><span class="glyphicon glyphicon-asterisk"></span></dt>
                            <dd>关于我们</dd>
                        </dl>
                    </a>
                </li>
            </ul>
        </menu>
        <p><a href="{% url 'axf:quit' %}">退出当前账号</a></p>
    </section>
    </div>
{% endblock base %}

Django_MKarry/templates/axf/register.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}

{% block linkscript %}
    <link rel="stylesheet" type="text/css" href="{% static 'mine/css/register.css' %}">
    <script type="text/javascript" charset="utf-8" src="{% static 'mine/js/register.js' %}"></script>
{% endblock linkscript %}

{% block base %}
    <div id="register">
        <div id="header">
            <a href="{% url 'axf:mine' %}"><p>&lt;返回</p></a>
        </div>
        <form action="{% url 'axf:register' %}" class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group">
                <span class="input-group-addon">账号</span>
                <input type="text" id="account" class="form-control" placeholder="账号长度为8个数组字符" aria-describedby="basic-addon1" name="userAccount">
            </div>
            <span id="accounterr" class="error">账号格式输入错误</span>
            <span id="checkerr" class="error">账号已经被占用，请重新输入</span>
            <br/>
            <div class="input-group">
                <span class="input-group-addon">密码</span>
                <input type="password" id="pass" class="form-control" placeholder="密码长度为6-16个字符" aria-describedby="basic-addon1" name="userPass">
            </div>
            <span id="passerr" class="error">密码格式输入错误</span>
            <br/>
            <div class="input-group">
                <span class="input-group-addon">验证</span>
                <input type="password" id="passwd" class="form-control" placeholder="密码长度为6-16个字符" aria-describedby="basic-addon1" name="userPasswd">
            </div>
            <span id="passwderr" class="error">两次密码输入不同</span>
            <br/>
            <div class="input-group">
                <span class="input-group-addon">昵称</span>
                <input type="text" required="required" class="form-control" aria-describedby="basic-addon1" name="userName">
            </div>
            <br/>
            <div class="input-group">
            <span class="input-group-addon">电话</span>
            <input required="required" type="text" class="form-control" aria-describedby="basic-addon1" name="userPhone">
        </div>
        <br/>
        <div class="input-group">
            <span class="input-group-addon">地址</span>
            <input required="required" type="text" class="form-control" aria-describedby="basic-addon1" name="userAdderss">
        </div>
        <br/>
        <div class="input-group">
            <span class="input-group-addon">头像</span>
            <input required="required" type="file" class="form-control" aria-describedby="basic-addon1" name="picture">
        </div>
        <br/>
        <div class="input-group">
            <span class="input-group-addon">注册</span>
            <input type="submit" class="form-control" aria-describedby="basic-addon1" value="注册">
        </div>
        </form>
    </div>
{% endblock base %}